-- Create a table to store anonymous device logs
create table if not exists app_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_agent text,
  screen_width int,
  screen_height int,
  language text,
  platform text,
  group_id text
);

-- Enable Row Level Security (RLS)
alter table app_logs enable row level security;

-- Create a policy to allow anyone to insert logs (anonymous logging)
create policy "Allow anonymous inserts"
on app_logs for insert
with check (true);

-- Create a policy to allow reading logs (optional, maybe restrict to authenticated users in future)
create policy "Allow public read access"
on app_logs for select
using (true);
